#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/config"


MANAGER_SCRIPT="$(dirname "$0")/mysql_manager"

manage() {
	bash $MANAGER_SCRIPT $*
}

restart_app() {
	dokku_log_info1_quiet "Restarting application: $APP"
	dokku release $APP
	dokku deploy $APP
}

restart_apps() {
	dokku_log_info1_quiet "Restarting applications"

	local apps=()

	for dir in $(ls $PLUGIN_DATA_ROOT); do
		while read line; do
			apps+=("$line")
		done < "$PLUGIN_DATA_ROOT/$dir/LINKS"
	done

	apps=$(echo "${apps[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
	for item in $apps; do
		restart_app $item
	done
}

get_container_id() {
	cat $PLUGIN_DATA_ROOT/CONTAINER_ID
}

get_admin_password() {
	cat $PLUGIN_DATA_ROOT/ROOTPASSWORD
}

generate_database_name() {
	echo "$1" | cut -c 1-16 | tr .- _
}

generate_random_string() {
	local LENGTH=$1
	openssl rand -hex $LENGTH
}

get_database_url() {
	local DB=$1
	local PW=$2
	echo "$PLUGIN_SCHEME://$DB:$PW@$PLUGIN_DATABASE_ALIAS:$PLUGIN_DATABASE_PORT/$DB"
}
