#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$0")/config"
source "$(dirname "$0")/functions"

APP="$1"
for db in $(get_all_databases); do
	sed -i "/^$APP\$/d" "$PLUGIN_DATA_ROOT/$db/LINKS" || true
done
